sudo: required

language: generic

services:
  - docker

befor_install:
  - echo "start creating an image with dockerfile"
  -docker build -t kumisnu/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kuminsu/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"